(function () {
  "use strict";
  window.NaituanDecor = {
  "themes": [
    {
      "id": "peach",
      "name": "杏桃奶油屋"
    },
    {
      "id": "garden",
      "name": "奶油绿田园"
    },
    {
      "id": "japanese",
      "name": "日式榻榻米"
    },
    {
      "id": "coastal",
      "name": "海边小屋"
    },
    {
      "id": "forest",
      "name": "森林树屋"
    },
    {
      "id": "attic",
      "name": "星月阁楼"
    }
  ],
  "rooms": [
    {
      "id": "scene-japanese",
      "floorBoundary": [[0, 0.565], [0.15, 0.50], [0.80, 0.50], [1, 0.615]],
      "name": "日式榻榻米",
      "price": 2999,
      "theme": "japanese",
      "image": "assets/decor/japanese/room.webp"
    },
    {
      "id": "scene-coastal",
      "floorBoundary": [[0, 0.604], [0.067, 0.574], [0.978, 0.574], [1, 0.589]],
      "name": "海边小屋",
      "price": 3299,
      "theme": "coastal",
      "image": "assets/decor/coastal/room.webp"
    },
    {
      "id": "scene-forest",
      "floorBoundary": [[0, 0.623], [0.15, 0.57], [0.44, 0.51], [0.62, 0.51], [0.92, 0.577], [1, 0.622]],
      "name": "森林树屋",
      "price": 3599,
      "theme": "forest",
      "image": "assets/decor/forest/room.webp"
    },
    {
      "id": "scene-attic",
      "floorBoundary": [[0, 0.72], [0.42, 0.535], [0.92, 0.535], [1, 0.584]],
      "name": "星月阁楼",
      "price": 3999,
      "theme": "attic",
      "image": "assets/decor/attic/room.webp"
    }
  ],
  "items": [
    {
      "id": "japanese-futon",
      "name": "日式地铺",
      "price": 1999,
      "theme": "japanese",
      "image": "assets/decor/japanese/01-futon.webp",
      "placement": "floor",
      "width": 341,
      "height": 208,
      "x": 0.75,
      "y": 0.57,
      "w": 0.45
    },
    {
      "id": "japanese-tansu",
      "name": "阶梯柜",
      "price": 2499,
      "theme": "japanese",
      "image": "assets/decor/japanese/02-tansu.webp",
      "placement": "floor",
      "width": 299,
      "height": 276,
      "x": 0.16,
      "y": 0.44,
      "w": 0.29
    },
    {
      "id": "japanese-tea-table",
      "name": "矮茶桌",
      "price": 999,
      "theme": "japanese",
      "image": "assets/decor/japanese/03-tea-table.webp",
      "placement": "floor",
      "width": 323,
      "height": 202,
      "x": 0.2,
      "y": 0.69,
      "w": 0.35
    },
    {
      "id": "japanese-basket-bed",
      "name": "藤编猫窝",
      "price": 899,
      "theme": "japanese",
      "image": "assets/decor/japanese/04-basket-bed.webp",
      "placement": "floor",
      "width": 305,
      "height": 209,
      "x": 0.84,
      "y": 0.78,
      "w": 0.27
    },
    {
      "id": "japanese-zabuton",
      "name": "蓝花坐垫",
      "price": 299,
      "theme": "japanese",
      "image": "assets/decor/japanese/05-zabuton.webp",
      "placement": "floor",
      "width": 315,
      "height": 215,
      "x": 0.29,
      "y": 0.85,
      "w": 0.18
    },
    {
      "id": "japanese-round-mat",
      "name": "圆编织垫",
      "price": 399,
      "theme": "japanese",
      "image": "assets/decor/japanese/06-round-mat.webp",
      "placement": "rug",
      "width": 313,
      "height": 177,
      "x": 0.5,
      "y": 0.81,
      "w": 0.2
    },
    {
      "id": "japanese-scratch-arch",
      "name": "拱形猫抓板",
      "price": 699,
      "theme": "japanese",
      "image": "assets/decor/japanese/07-scratch-arch.webp",
      "placement": "floor",
      "width": 312,
      "height": 217,
      "x": 0.83,
      "y": 0.92,
      "w": 0.21
    },
    {
      "id": "japanese-paper-lantern",
      "name": "纸球吊灯",
      "price": 799,
      "theme": "japanese",
      "image": "assets/decor/japanese/08-paper-lantern.webp",
      "placement": "ceiling",
      "width": 256,
      "height": 304,
      "x": 0.5,
      "y": 0.16,
      "w": 0.25
    },
    {
      "id": "japanese-floor-lantern",
      "name": "木框灯笼",
      "price": 599,
      "theme": "japanese",
      "image": "assets/decor/japanese/09-floor-lantern.webp",
      "placement": "surface",
      "width": 171,
      "height": 299,
      "x": 0.14,
      "y": 0.32,
      "w": 0.1
    },
    {
      "id": "japanese-scroll",
      "name": "花卉挂轴",
      "price": 399,
      "theme": "japanese",
      "image": "assets/decor/japanese/10-scroll.webp",
      "placement": "wall",
      "width": 166,
      "height": 336,
      "x": 0.89,
      "y": 0.28,
      "w": 0.13
    },
    {
      "id": "japanese-tall-vase",
      "name": "花枝高花瓶",
      "price": 299,
      "theme": "japanese",
      "image": "assets/decor/japanese/11-tall-vase.webp",
      "placement": "surface",
      "width": 262,
      "height": 343,
      "x": 0.89,
      "y": 0.46,
      "w": 0.1
    },
    {
      "id": "japanese-blossom-vase",
      "name": "桃花小瓶",
      "price": 199,
      "theme": "japanese",
      "image": "assets/decor/japanese/12-blossom-vase.webp",
      "placement": "surface",
      "width": 221,
      "height": 302,
      "x": 0.23,
      "y": 0.43,
      "w": 0.09
    },
    {
      "id": "japanese-plant",
      "name": "小盆栽",
      "price": 199,
      "theme": "japanese",
      "image": "assets/decor/japanese/13-plant.webp",
      "placement": "surface",
      "width": 293,
      "height": 283,
      "x": 0.11,
      "y": 0.25,
      "w": 0.1
    },
    {
      "id": "japanese-flower-vase",
      "name": "小花瓶",
      "price": 199,
      "theme": "japanese",
      "image": "assets/decor/japanese/14-flower-vase.webp",
      "placement": "surface",
      "width": 245,
      "height": 293,
      "x": 0.19,
      "y": 0.65,
      "w": 0.08
    },
    {
      "id": "japanese-tea-cup",
      "name": "茶杯碟",
      "price": 100,
      "theme": "japanese",
      "image": "assets/decor/japanese/15-tea-cup.webp",
      "placement": "surface",
      "width": 273,
      "height": 212,
      "x": 0.27,
      "y": 0.68,
      "w": 0.07
    },
    {
      "id": "japanese-bolster",
      "name": "蓝色圆枕",
      "price": 199,
      "theme": "japanese",
      "image": "assets/decor/japanese/16-bolster.webp",
      "placement": "surface",
      "width": 304,
      "height": 181,
      "x": 0.87,
      "y": 0.55,
      "w": 0.1
    },
    {
      "id": "coastal-window-bench",
      "name": "条纹窗台床",
      "price": 2499,
      "theme": "coastal",
      "image": "assets/decor/coastal/01-window-bench.webp",
      "placement": "floor",
      "width": 467,
      "height": 203,
      "x": 0.5,
      "y": 0.57,
      "w": 0.53
    },
    {
      "id": "coastal-boat-shelf",
      "name": "船形书架",
      "price": 1999,
      "theme": "coastal",
      "image": "assets/decor/coastal/02-boat-shelf.webp",
      "placement": "floor",
      "width": 212,
      "height": 387,
      "x": 0.15,
      "y": 0.43,
      "w": 0.24
    },
    {
      "id": "coastal-hanging-chair",
      "name": "藤编吊椅",
      "price": 2299,
      "theme": "coastal",
      "image": "assets/decor/coastal/03-hanging-chair.webp",
      "placement": "ceiling",
      "width": 266,
      "height": 399,
      "x": 0.82,
      "y": 0.34,
      "w": 0.27
    },
    {
      "id": "coastal-trunk-table",
      "name": "木箱茶几",
      "price": 1499,
      "theme": "coastal",
      "image": "assets/decor/coastal/04-trunk-table.webp",
      "placement": "floor",
      "width": 293,
      "height": 209,
      "x": 0.19,
      "y": 0.78,
      "w": 0.34
    },
    {
      "id": "coastal-lighthouse-bed",
      "name": "灯塔猫窝",
      "price": 799,
      "theme": "coastal",
      "image": "assets/decor/coastal/05-lighthouse-bed.webp",
      "placement": "floor",
      "width": 238,
      "height": 350,
      "x": 0.85,
      "y": 0.77,
      "w": 0.19
    },
    {
      "id": "coastal-scratch-post",
      "name": "原木猫抓柱",
      "price": 799,
      "theme": "coastal",
      "image": "assets/decor/coastal/06-scratch-post.webp",
      "placement": "floor",
      "width": 206,
      "height": 263,
      "x": 0.82,
      "y": 0.91,
      "w": 0.14
    },
    {
      "id": "coastal-wave-rug",
      "name": "波浪地毯",
      "price": 699,
      "theme": "coastal",
      "image": "assets/decor/coastal/07-wave-rug.webp",
      "placement": "rug",
      "width": 469,
      "height": 279,
      "x": 0.5,
      "y": 0.82,
      "w": 0.61
    },
    {
      "id": "coastal-lantern",
      "name": "航海吊灯",
      "price": 699,
      "theme": "coastal",
      "image": "assets/decor/coastal/08-lantern.webp",
      "placement": "ceiling",
      "width": 147,
      "height": 318,
      "x": 0.61,
      "y": 0.18,
      "w": 0.1
    },
    {
      "id": "coastal-shell-cushion",
      "name": "贝壳抱枕",
      "price": 299,
      "theme": "coastal",
      "image": "assets/decor/coastal/09-shell-cushion.webp",
      "placement": "surface",
      "width": 264,
      "height": 220,
      "x": 0.53,
      "y": 0.5,
      "w": 0.14
    },
    {
      "id": "coastal-star-cushion",
      "name": "星星抱枕",
      "price": 299,
      "theme": "coastal",
      "image": "assets/decor/coastal/10-star-cushion.webp",
      "placement": "surface",
      "width": 267,
      "height": 241,
      "x": 0.32,
      "y": 0.5,
      "w": 0.15
    },
    {
      "id": "coastal-square-cushion",
      "name": "海蓝方枕",
      "price": 249,
      "theme": "coastal",
      "image": "assets/decor/coastal/11-square-cushion.webp",
      "placement": "surface",
      "width": 255,
      "height": 244,
      "x": 0.84,
      "y": 0.45,
      "w": 0.13
    },
    {
      "id": "coastal-daisy-vase",
      "name": "雏菊花瓶",
      "price": 199,
      "theme": "coastal",
      "image": "assets/decor/coastal/12-daisy-vase.webp",
      "placement": "surface",
      "width": 252,
      "height": 282,
      "x": 0.19,
      "y": 0.68,
      "w": 0.09
    },
    {
      "id": "coastal-books",
      "name": "海边书组",
      "price": 149,
      "theme": "coastal",
      "image": "assets/decor/coastal/13-books.webp",
      "placement": "surface",
      "width": 209,
      "height": 231,
      "x": 0.13,
      "y": 0.46,
      "w": 0.07
    },
    {
      "id": "coastal-shell-coral",
      "name": "贝壳珊瑚摆件",
      "price": 199,
      "theme": "coastal",
      "image": "assets/decor/coastal/14-shell-coral.webp",
      "placement": "surface",
      "width": 285,
      "height": 196,
      "x": 0.15,
      "y": 0.35,
      "w": 0.09
    },
    {
      "id": "coastal-vine",
      "name": "垂藤盆栽",
      "price": 299,
      "theme": "coastal",
      "image": "assets/decor/coastal/15-vine.webp",
      "placement": "surface",
      "width": 991,
      "height": 880,
      "x": 0.9,
      "y": 0.14,
      "w": 0.1
    },
    {
      "id": "coastal-cup",
      "name": "马克杯碟",
      "price": 100,
      "theme": "coastal",
      "image": "assets/decor/coastal/16-cup.webp",
      "placement": "surface",
      "width": 230,
      "height": 189,
      "x": 0.26,
      "y": 0.71,
      "w": 0.06
    },
    {
      "id": "forest-hollow-bed",
      "name": "树洞床",
      "price": 2999,
      "theme": "forest",
      "image": "assets/decor/forest/01-hollow-bed.webp",
      "placement": "floor",
      "width": 453,
      "height": 400,
      "x": 0.18,
      "y": 0.43,
      "w": 0.36
    },
    {
      "id": "forest-stove",
      "name": "暖炉烟囱",
      "price": 1999,
      "theme": "forest",
      "image": "assets/decor/forest/02-stove.webp",
      "placement": "floor",
      "width": 296,
      "height": 422,
      "x": 0.86,
      "y": 0.42,
      "w": 0.24
    },
    {
      "id": "forest-stump-table",
      "name": "树桩茶几",
      "price": 999,
      "theme": "forest",
      "image": "assets/decor/forest/03-stump-table.webp",
      "placement": "floor",
      "width": 340,
      "height": 236,
      "x": 0.17,
      "y": 0.73,
      "w": 0.27
    },
    {
      "id": "forest-mushroom-stool",
      "name": "蘑菇凳",
      "price": 599,
      "theme": "forest",
      "image": "assets/decor/forest/04-mushroom-stool.webp",
      "placement": "floor",
      "width": 231,
      "height": 219,
      "x": 0.24,
      "y": 0.89,
      "w": 0.16
    },
    {
      "id": "forest-leaf-rug",
      "name": "叶子地毯",
      "price": 799,
      "theme": "forest",
      "image": "assets/decor/forest/05-leaf-rug.webp",
      "placement": "rug",
      "width": 517,
      "height": 309,
      "x": 0.5,
      "y": 0.81,
      "w": 0.63
    },
    {
      "id": "forest-acorn-bed",
      "name": "橡果猫窝",
      "price": 1499,
      "theme": "forest",
      "image": "assets/decor/forest/06-acorn-bed.webp",
      "placement": "floor",
      "width": 324,
      "height": 342,
      "x": 0.86,
      "y": 0.86,
      "w": 0.25
    },
    {
      "id": "forest-branch-scratcher",
      "name": "树枝猫抓柱",
      "price": 799,
      "theme": "forest",
      "image": "assets/decor/forest/07-branch-scratcher.webp",
      "placement": "floor",
      "width": 198,
      "height": 320,
      "x": 0.92,
      "y": 0.88,
      "w": 0.13
    },
    {
      "id": "forest-acorn-lamp",
      "name": "橡果吊灯",
      "price": 899,
      "theme": "forest",
      "image": "assets/decor/forest/08-acorn-lamp.webp",
      "placement": "ceiling",
      "width": 177,
      "height": 306,
      "x": 0.5,
      "y": 0.18,
      "w": 0.14
    },
    {
      "id": "forest-branch-shelf",
      "name": "树枝壁架",
      "price": 399,
      "theme": "forest",
      "image": "assets/decor/forest/09-branch-shelf.webp",
      "placement": "wall",
      "width": 362,
      "height": 184,
      "x": 0.85,
      "y": 0.26,
      "w": 0.24
    },
    {
      "id": "forest-vine",
      "name": "垂藤盆栽",
      "price": 299,
      "theme": "forest",
      "image": "assets/decor/forest/10-vine.webp",
      "placement": "surface",
      "width": 311,
      "height": 316,
      "x": 0.77,
      "y": 0.23,
      "w": 0.13
    },
    {
      "id": "forest-flower-vase",
      "name": "雏菊花瓶",
      "price": 199,
      "theme": "forest",
      "image": "assets/decor/forest/11-flower-vase.webp",
      "placement": "surface",
      "width": 217,
      "height": 243,
      "x": 0.13,
      "y": 0.64,
      "w": 0.09
    },
    {
      "id": "forest-leaf-cushion",
      "name": "叶子抱枕",
      "price": 299,
      "theme": "forest",
      "image": "assets/decor/forest/12-leaf-cushion.webp",
      "placement": "surface",
      "width": 247,
      "height": 247,
      "x": 0.15,
      "y": 0.37,
      "w": 0.13
    },
    {
      "id": "forest-logs",
      "name": "木柴堆",
      "price": 199,
      "theme": "forest",
      "image": "assets/decor/forest/13-logs.webp",
      "placement": "floor",
      "width": 305,
      "height": 214,
      "x": 0.92,
      "y": 0.6,
      "w": 0.15
    },
    {
      "id": "forest-books",
      "name": "森林书组",
      "price": 149,
      "theme": "forest",
      "image": "assets/decor/forest/14-books.webp",
      "placement": "surface",
      "width": 241,
      "height": 239,
      "x": 0.86,
      "y": 0.34,
      "w": 0.09
    },
    {
      "id": "forest-mushroom-ornament",
      "name": "蘑菇摆件",
      "price": 100,
      "theme": "forest",
      "image": "assets/decor/forest/15-mushroom-ornament.webp",
      "placement": "surface",
      "width": 182,
      "height": 189,
      "x": 0.93,
      "y": 0.32,
      "w": 0.06
    },
    {
      "id": "forest-cup",
      "name": "茶杯碟",
      "price": 100,
      "theme": "forest",
      "image": "assets/decor/forest/16-cup.webp",
      "placement": "surface",
      "width": 221,
      "height": 181,
      "x": 0.24,
      "y": 0.7,
      "w": 0.06
    },
    {
      "id": "attic-loft-unit",
      "name": "复式床阅读架",
      "price": 3299,
      "theme": "attic",
      "image": "assets/decor/attic/01-loft-unit.webp",
      "placement": "floor",
      "width": 356,
      "height": 327,
      "x": 0.64,
      "y": 0.4,
      "w": 0.46
    },
    {
      "id": "attic-storage-stairs",
      "name": "储物楼梯",
      "price": 1699,
      "theme": "attic",
      "image": "assets/decor/attic/02-storage-stairs.webp",
      "placement": "floor",
      "width": 237,
      "height": 330,
      "x": 0.91,
      "y": 0.5,
      "w": 0.15
    },
    {
      "id": "attic-moon-shelf",
      "name": "月牙书架",
      "price": 1999,
      "theme": "attic",
      "image": "assets/decor/attic/03-moon-shelf.webp",
      "placement": "floor",
      "width": 274,
      "height": 318,
      "x": 0.32,
      "y": 0.46,
      "w": 0.23
    },
    {
      "id": "attic-desk",
      "name": "原木书桌",
      "price": 1299,
      "theme": "attic",
      "image": "assets/decor/attic/04-desk.webp",
      "placement": "floor",
      "width": 325,
      "height": 232,
      "x": 0.16,
      "y": 0.6,
      "w": 0.3
    },
    {
      "id": "attic-pouf",
      "name": "紫色圆坐墩",
      "price": 699,
      "theme": "attic",
      "image": "assets/decor/attic/05-pouf.webp",
      "placement": "floor",
      "width": 265,
      "height": 193,
      "x": 0.17,
      "y": 0.73,
      "w": 0.21
    },
    {
      "id": "attic-reading-cushion",
      "name": "阅读软垫",
      "price": 899,
      "theme": "attic",
      "image": "assets/decor/attic/06-reading-cushion.webp",
      "placement": "floor",
      "width": 341,
      "height": 228,
      "x": 0.62,
      "y": 0.56,
      "w": 0.28
    },
    {
      "id": "attic-cloud-rug",
      "name": "云朵地毯",
      "price": 799,
      "theme": "attic",
      "image": "assets/decor/attic/07-cloud-rug.webp",
      "placement": "rug",
      "width": 358,
      "height": 197,
      "x": 0.5,
      "y": 0.84,
      "w": 0.67
    },
    {
      "id": "attic-moon-bed",
      "name": "月牙猫窝",
      "price": 1499,
      "theme": "attic",
      "image": "assets/decor/attic/08-moon-bed.webp",
      "placement": "floor",
      "width": 269,
      "height": 237,
      "x": 0.8,
      "y": 0.92,
      "w": 0.25
    },
    {
      "id": "attic-rocket-scratcher",
      "name": "火箭猫抓柱",
      "price": 999,
      "theme": "attic",
      "image": "assets/decor/attic/09-rocket-scratcher.webp",
      "placement": "floor",
      "width": 193,
      "height": 282,
      "x": 0.91,
      "y": 0.74,
      "w": 0.13
    },
    {
      "id": "attic-telescope",
      "name": "望远镜",
      "price": 1299,
      "theme": "attic",
      "image": "assets/decor/attic/10-telescope.webp",
      "placement": "surface",
      "width": 268,
      "height": 280,
      "x": 0.17,
      "y": 0.47,
      "w": 0.17
    },
    {
      "id": "attic-star-lamp",
      "name": "星星吊灯",
      "price": 499,
      "theme": "attic",
      "image": "assets/decor/attic/11-star-lamp.webp",
      "placement": "ceiling",
      "width": 171,
      "height": 275,
      "x": 0.53,
      "y": 0.13,
      "w": 0.09
    },
    {
      "id": "attic-star-cushion",
      "name": "星星抱枕",
      "price": 299,
      "theme": "attic",
      "image": "assets/decor/attic/12-star-cushion.webp",
      "placement": "surface",
      "width": 250,
      "height": 226,
      "x": 0.36,
      "y": 0.83,
      "w": 0.13
    },
    {
      "id": "attic-moon-picture",
      "name": "月亮挂画",
      "price": 249,
      "theme": "attic",
      "image": "assets/decor/attic/13-moon-picture.webp",
      "placement": "wall",
      "width": 215,
      "height": 230,
      "x": 0.91,
      "y": 0.29,
      "w": 0.07
    },
    {
      "id": "attic-vine",
      "name": "垂藤盆栽",
      "price": 299,
      "theme": "attic",
      "image": "assets/decor/attic/14-vine.webp",
      "placement": "surface",
      "width": 296,
      "height": 313,
      "x": 0.74,
      "y": 0.34,
      "w": 0.12
    },
    {
      "id": "attic-books-notebook",
      "name": "书本笔记本",
      "price": 199,
      "theme": "attic",
      "image": "assets/decor/attic/15-books-notebook.webp",
      "placement": "surface",
      "width": 335,
      "height": 230,
      "x": 0.22,
      "y": 0.59,
      "w": 0.13
    },
    {
      "id": "attic-table-lamp",
      "name": "阅读台灯",
      "price": 599,
      "theme": "attic",
      "image": "assets/decor/attic/16-table-lamp.webp",
      "placement": "surface",
      "width": 215,
      "height": 248,
      "x": 0.65,
      "y": 0.49,
      "w": 0.08
    },
    {
      "id": "peach-window",
      "name": "杏桃窗帘窗",
      "price": 399,
      "theme": "peach",
      "image": "assets/decor/peach/window.webp",
      "placement": "window",
      "width": 754,
      "height": 475,
      "x": 0.32,
      "y": 0.25,
      "w": 0.48
    },
    {
      "id": "peach-flower-art",
      "name": "杏桃花朵画",
      "price": 149,
      "theme": "peach",
      "image": "assets/decor/peach/flower-art.webp",
      "placement": "wall",
      "width": 218,
      "height": 249,
      "x": 0.65,
      "y": 0.24,
      "w": 0.15
    },
    {
      "id": "peach-moon-art",
      "name": "晚安月亮画",
      "price": 149,
      "theme": "peach",
      "image": "assets/decor/peach/moon-art.webp",
      "placement": "wall",
      "width": 214,
      "height": 223,
      "x": 0.81,
      "y": 0.25,
      "w": 0.13
    },
    {
      "id": "peach-clock",
      "name": "杏桃圆挂钟",
      "price": 199,
      "theme": "peach",
      "image": "assets/decor/peach/clock.webp",
      "placement": "wall",
      "width": 260,
      "height": 254,
      "x": 0.87,
      "y": 0.16,
      "w": 0.14
    },
    {
      "id": "peach-plant",
      "name": "杏桃小盆栽",
      "price": 129,
      "theme": "peach",
      "image": "assets/decor/peach/plant.webp",
      "placement": "surface",
      "width": 179,
      "height": 195,
      "x": 0.32,
      "y": 0.56,
      "w": 0.1
    },
    {
      "id": "peach-cup",
      "name": "杏桃咖啡杯",
      "price": 100,
      "theme": "peach",
      "image": "assets/decor/peach/cup.webp",
      "placement": "surface",
      "width": 201,
      "height": 158,
      "x": 0.73,
      "y": 0.7,
      "w": 0.1
    },
    {
      "id": "peach-rug",
      "name": "杏桃云朵地毯",
      "price": 299,
      "theme": "peach",
      "image": "assets/decor/peach/rug.webp",
      "placement": "rug",
      "width": 1177,
      "height": 347,
      "x": 0.5,
      "y": 0.8,
      "w": 0.68
    },
    {
      "id": "garden-bed",
      "name": "田园格纹木床",
      "price": 500,
      "theme": "garden",
      "image": "assets/decor/garden/bed.webp",
      "placement": "floor",
      "width": 463,
      "height": 439,
      "x": 0.16,
      "y": 0.58,
      "w": 0.3
    },
    {
      "id": "garden-cabinet",
      "name": "奶油双抽床头柜",
      "price": 299,
      "theme": "garden",
      "image": "assets/decor/garden/cabinet.webp",
      "placement": "floor",
      "width": 289,
      "height": 294,
      "x": 0.34,
      "y": 0.59,
      "w": 0.16
    },
    {
      "id": "garden-shelf",
      "name": "藤叶拱形书柜",
      "price": 399,
      "theme": "garden",
      "image": "assets/decor/garden/shelf.webp",
      "placement": "floor",
      "width": 366,
      "height": 370,
      "x": 0.5,
      "y": 0.55,
      "w": 0.2
    },
    {
      "id": "garden-sofa",
      "name": "雏菊奶油沙发",
      "price": 499,
      "theme": "garden",
      "image": "assets/decor/garden/sofa.webp",
      "placement": "floor",
      "width": 543,
      "height": 343,
      "x": 0.77,
      "y": 0.57,
      "w": 0.34
    },
    {
      "id": "garden-table",
      "name": "田园椭圆茶几",
      "price": 299,
      "theme": "garden",
      "image": "assets/decor/garden/table.webp",
      "placement": "floor",
      "width": 437,
      "height": 205,
      "x": 0.73,
      "y": 0.72,
      "w": 0.27
    },
    {
      "id": "garden-lamp",
      "name": "花边田园落地灯",
      "price": 249,
      "theme": "garden",
      "image": "assets/decor/garden/lamp.webp",
      "placement": "floor",
      "width": 222,
      "height": 391,
      "x": 0.93,
      "y": 0.53,
      "w": 0.13
    },
    {
      "id": "garden-cat-bed",
      "name": "雏菊软软猫窝",
      "price": 299,
      "theme": "garden",
      "image": "assets/decor/garden/cat-bed.webp",
      "placement": "floor",
      "width": 441,
      "height": 268,
      "x": 0.17,
      "y": 0.89,
      "w": 0.24
    },
    {
      "id": "garden-scratcher",
      "name": "草绿猫抓柱",
      "price": 249,
      "theme": "garden",
      "image": "assets/decor/garden/scratcher.webp",
      "placement": "floor",
      "width": 273,
      "height": 296,
      "x": 0.89,
      "y": 0.88,
      "w": 0.13
    },
    {
      "id": "garden-window",
      "name": "格纹花园窗",
      "price": 399,
      "theme": "garden",
      "image": "assets/decor/garden/window.webp",
      "placement": "window",
      "width": 652,
      "height": 438,
      "x": 0.31,
      "y": 0.25,
      "w": 0.46
    },
    {
      "id": "garden-daisy-art",
      "name": "雏菊花束画",
      "price": 149,
      "theme": "garden",
      "image": "assets/decor/garden/daisy-art.webp",
      "placement": "wall",
      "width": 268,
      "height": 344,
      "x": 0.63,
      "y": 0.23,
      "w": 0.15
    },
    {
      "id": "garden-leaf-art",
      "name": "嫩叶小挂画",
      "price": 149,
      "theme": "garden",
      "image": "assets/decor/garden/leaf-art.webp",
      "placement": "wall",
      "width": 251,
      "height": 263,
      "x": 0.77,
      "y": 0.24,
      "w": 0.12
    },
    {
      "id": "garden-clock",
      "name": "蜂蜜木圆挂钟",
      "price": 199,
      "theme": "garden",
      "image": "assets/decor/garden/clock.webp",
      "placement": "wall",
      "width": 330,
      "height": 330,
      "x": 0.89,
      "y": 0.16,
      "w": 0.14
    },
    {
      "id": "garden-plant",
      "name": "田园小盆栽",
      "price": 129,
      "theme": "garden",
      "image": "assets/decor/garden/plant.webp",
      "placement": "surface",
      "width": 275,
      "height": 262,
      "x": 0.33,
      "y": 0.47,
      "w": 0.1
    },
    {
      "id": "garden-cup",
      "name": "嫩叶咖啡杯",
      "price": 100,
      "theme": "garden",
      "image": "assets/decor/garden/cup.webp",
      "placement": "surface",
      "width": 254,
      "height": 213,
      "x": 0.73,
      "y": 0.65,
      "w": 0.09
    },
    {
      "id": "garden-rug",
      "name": "雏菊草地毯",
      "price": 299,
      "theme": "garden",
      "image": "assets/decor/garden/rug.webp",
      "placement": "rug",
      "width": 681,
      "height": 313,
      "x": 0.5,
      "y": 0.8,
      "w": 0.65
    },
    {
      "id": "peach-bed",
      "name": "杏桃软被木床",
      "price": 500,
      "theme": "peach",
      "image": "assets/decor/peach/bed.webp",
      "placement": "floor",
      "width": 406,
      "height": 363,
      "x": 0.16,
      "y": 0.58,
      "w": 0.3
    },
    {
      "id": "peach-sofa",
      "name": "杏桃奶油沙发",
      "price": 499,
      "theme": "peach",
      "image": "assets/decor/peach/sofa.webp",
      "placement": "floor",
      "width": 481,
      "height": 325,
      "x": 0.77,
      "y": 0.57,
      "w": 0.34
    },
    {
      "id": "peach-table",
      "name": "杏桃椭圆茶几",
      "price": 299,
      "theme": "peach",
      "image": "assets/decor/peach/table.webp",
      "placement": "floor",
      "width": 368,
      "height": 225,
      "x": 0.73,
      "y": 0.72,
      "w": 0.27
    },
    {
      "id": "peach-cabinet",
      "name": "杏桃双抽床头柜",
      "price": 299,
      "theme": "peach",
      "image": "assets/decor/peach/cabinet.webp",
      "placement": "floor",
      "width": 326,
      "height": 323,
      "x": 0.34,
      "y": 0.59,
      "w": 0.16
    },
    {
      "id": "peach-shelf",
      "name": "杏桃圆角书柜",
      "price": 399,
      "theme": "peach",
      "image": "assets/decor/peach/shelf.webp",
      "placement": "floor",
      "width": 430,
      "height": 341,
      "x": 0.5,
      "y": 0.55,
      "w": 0.23
    },
    {
      "id": "peach-lamp",
      "name": "杏桃花边落地灯",
      "price": 249,
      "theme": "peach",
      "image": "assets/decor/peach/lamp.webp",
      "placement": "floor",
      "width": 272,
      "height": 423,
      "x": 0.93,
      "y": 0.53,
      "w": 0.13
    },
    {
      "id": "peach-cat-bed",
      "depthAware": true,
      "name": "杏桃软软猫窝",
      "price": 299,
      "theme": "peach",
      "image": "assets/decor/peach/cat-bed.webp",
      "placement": "floor",
      "width": 462,
      "height": 296,
      "x": 0.17,
      "y": 0.89,
      "w": 0.24
    },
    {
      "id": "peach-scratcher",
      "name": "杏桃猫抓柱",
      "price": 249,
      "theme": "peach",
      "image": "assets/decor/peach/scratcher.webp",
      "placement": "floor",
      "width": 309,
      "height": 356,
      "x": 0.89,
      "y": 0.88,
      "w": 0.14
    },
    {
      "id": "peach-stool",
      "name": "杏桃软垫小凳",
      "price": 199,
      "theme": "peach",
      "image": "assets/decor/peach/stool.webp",
      "placement": "floor",
      "width": 281,
      "height": 267,
      "x": 0.34,
      "y": 0.86,
      "w": 0.15
    }
  ]
};
})();
